platform :ios, '11.0'

def utils
  pod 'SwiftGen', '6.1.0'
  pod 'SwiftLint', '0.30.1'
end

def common_pods
  utils
  pod 'SurfUtils/XibView', :git => 'https://github.com/surfstudio/iOS-Utils.git', :tag => '10.0.5'
  pod 'ReactiveDataDisplayManager', :git => 'https://github.com/surfstudio/ReactiveDataDisplayManager', :commit => '73122a834e7e90744dd828804afb32dbd48a83c6'
  pod 'SFOTPTextField', :path => '../'

end

target 'OTPTextFieldExample' do
  use_frameworks!
  common_pods
end
